i=imread('rose.jpg');
k=rgb2gray(i);
j=imnoise(k,'salt & pepper',0.05);
f=medfilt2(j,[3,3]);
f1=medfilt2(j,[10,10]);
subplot(3,2,1);
imshow(i);
title('original image');
subplot(3,2,2);
imshow(k);
title('gray image');
subplot(3,2,3);
imshow(j);
title('noise added image');
subplot(3,2,4);
imshow(f);
title('3x3 image');
subplot(3,2,5);
imshow(f1);
title('10x10 image');